version = 1

[[analyzers]]
name = "python"

[analyzers.meta]
runtime_version = "3.12.x"

# تجاهل الملفات الغير مهمة للتحليل
skip = [
  "build/**",
  "dist/**",
  "*.spec",
  "venv/**",
  ".venv/**",
  "__pycache__/**",
]

# تنسيقات الكود
[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true

