# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/EditEmployeePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditEmployeeDialog(object):
    def setupUi(self, EditEmployeeDialog):
        EditEmployeeDialog.setObjectName("EditEmployeeDialog")
        EditEmployeeDialog.resize(1135, 771)
        EditEmployeeDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        EditEmployeeDialog.setStyleSheet("QDialog {\n"
"    background-color: #f5f6fa;\n"
"}\n"
" QWidget {\n"
"    font: 11pt \"Dubai\";\n"
"}\n"
"QTreeView {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #d1d8e0;\n"
"    border-radius: 8px;\n"
"    alternate-background-color: #f0f3f7;\n"
"    gridline-color: #d1d8e0;\n"
"}\n"
"QTreeView::item {\n"
"    padding: 6px 10px;\n"
"}\n"
"QTreeView::item:selected {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}\n"
"QHeaderView {\n"
"    background-color: #ecf0f1;\n"
"    color: #2c3e50;\n"
"    border: 1px solid #d1d8e0;\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    padding: 2px 0px;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #ecf0f1;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    border-right: 1px solid #d1d8e0;\n"
"}\n"
"QHeaderView::section:pressed {\n"
"    background-color: #bdc3c7;\n"
"}\n"
"QHeaderView {\n"
"    qproperty-defaultAlignment: AlignCenter;\n"
"}\n"
"\n"
"/* Modern Buttons */\n"
"QPushButton {\n"
"    font: 12pt \"Dubai\";\n"
"    padding: 4px 20px;\n"
"}\n"
"\n"
"#EmployeeFrame, #label_photo {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #d1d8e0;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(EditEmployeeDialog)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(EditEmployeeDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.EmployeeFrame = QtWidgets.QFrame(self.tab)
        self.EmployeeFrame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.EmployeeFrame.setAutoFillBackground(False)
        self.EmployeeFrame.setObjectName("EmployeeFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.EmployeeFrame)
        self.gridLayout_2.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_2.setHorizontalSpacing(12)
        self.gridLayout_2.setVerticalSpacing(13)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_manage_departments = QtWidgets.QToolButton(self.EmployeeFrame)
        self.btn_manage_departments.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_manage_departments.setIcon(icon)
        self.btn_manage_departments.setIconSize(QtCore.QSize(28, 28))
        self.btn_manage_departments.setObjectName("btn_manage_departments")
        self.gridLayout_2.addWidget(self.btn_manage_departments, 11, 3, 1, 1)
        self.btn_manage_jobs = QtWidgets.QToolButton(self.EmployeeFrame)
        self.btn_manage_jobs.setText("")
        self.btn_manage_jobs.setIcon(icon)
        self.btn_manage_jobs.setIconSize(QtCore.QSize(28, 28))
        self.btn_manage_jobs.setObjectName("btn_manage_jobs")
        self.gridLayout_2.addWidget(self.btn_manage_jobs, 11, 1, 1, 1)
        self.name_ar = QtWidgets.QLineEdit(self.EmployeeFrame)
        self.name_ar.setObjectName("name_ar")
        self.gridLayout_2.addWidget(self.name_ar, 3, 0, 1, 2)
        self.job_title = QtWidgets.QComboBox(self.EmployeeFrame)
        self.job_title.setObjectName("job_title")
        self.gridLayout_2.addWidget(self.job_title, 11, 0, 1, 1)
        self.department = QtWidgets.QComboBox(self.EmployeeFrame)
        self.department.setObjectName("department")
        self.gridLayout_2.addWidget(self.department, 11, 2, 1, 1)
        self.label_name_ar = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_name_ar.setObjectName("label_name_ar")
        self.gridLayout_2.addWidget(self.label_name_ar, 2, 0, 1, 1)
        self.label_birth_date = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_birth_date.setObjectName("label_birth_date")
        self.gridLayout_2.addWidget(self.label_birth_date, 6, 0, 1, 1)
        self.label_job_title = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_job_title.setObjectName("label_job_title")
        self.gridLayout_2.addWidget(self.label_job_title, 10, 0, 1, 1)
        self.label_name_en = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_name_en.setObjectName("label_name_en")
        self.gridLayout_2.addWidget(self.label_name_en, 4, 0, 1, 1)
        self.label_department = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_department.setObjectName("label_department")
        self.gridLayout_2.addWidget(self.label_department, 10, 2, 1, 1)
        self.role_layout = QtWidgets.QHBoxLayout()
        self.role_layout.setObjectName("role_layout")
        self.label_role = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_role.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_role.setObjectName("label_role")
        self.role_layout.addWidget(self.label_role)
        self.role_user = QtWidgets.QRadioButton(self.EmployeeFrame)
        self.role_user.setObjectName("role_user")
        self.role_layout.addWidget(self.role_user)
        self.role_admin = QtWidgets.QRadioButton(self.EmployeeFrame)
        self.role_admin.setObjectName("role_admin")
        self.role_layout.addWidget(self.role_admin)
        self.gridLayout_2.addLayout(self.role_layout, 12, 0, 1, 2)
        self.birth_date = QtWidgets.QDateEdit(self.EmployeeFrame)
        self.birth_date.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 1, 1), QtCore.QTime(0, 0, 0)))
        self.birth_date.setCalendarPopup(True)
        self.birth_date.setObjectName("birth_date")
        self.gridLayout_2.addWidget(self.birth_date, 7, 0, 1, 2)
        self.name_en = QtWidgets.QLineEdit(self.EmployeeFrame)
        self.name_en.setObjectName("name_en")
        self.gridLayout_2.addWidget(self.name_en, 5, 0, 1, 2)
        self.label_phone = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_phone.setObjectName("label_phone")
        self.gridLayout_2.addWidget(self.label_phone, 8, 0, 1, 1)
        self.label_iban = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_iban.setObjectName("label_iban")
        self.gridLayout_2.addWidget(self.label_iban, 8, 2, 1, 1)
        self.label_id_expiry = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_id_expiry.setObjectName("label_id_expiry")
        self.gridLayout_2.addWidget(self.label_id_expiry, 6, 2, 1, 1)
        self.label_id_issue = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_id_issue.setObjectName("label_id_issue")
        self.gridLayout_2.addWidget(self.label_id_issue, 4, 2, 1, 1)
        self.label_national_id = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_national_id.setObjectName("label_national_id")
        self.gridLayout_2.addWidget(self.label_national_id, 2, 2, 1, 1)
        self.iban_number = QtWidgets.QLineEdit(self.EmployeeFrame)
        self.iban_number.setObjectName("iban_number")
        self.gridLayout_2.addWidget(self.iban_number, 9, 2, 1, 2)
        self.id_expiry_date = QtWidgets.QDateEdit(self.EmployeeFrame)
        self.id_expiry_date.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 1, 1), QtCore.QTime(0, 0, 0)))
        self.id_expiry_date.setCalendarPopup(True)
        self.id_expiry_date.setObjectName("id_expiry_date")
        self.gridLayout_2.addWidget(self.id_expiry_date, 7, 2, 1, 2)
        self.id_issue_date = QtWidgets.QDateEdit(self.EmployeeFrame)
        self.id_issue_date.setDateTime(QtCore.QDateTime(QtCore.QDate(1999, 1, 1), QtCore.QTime(0, 0, 0)))
        self.id_issue_date.setCalendarPopup(True)
        self.id_issue_date.setObjectName("id_issue_date")
        self.gridLayout_2.addWidget(self.id_issue_date, 5, 2, 1, 2)
        self.national_id = QtWidgets.QLineEdit(self.EmployeeFrame)
        self.national_id.setObjectName("national_id")
        self.gridLayout_2.addWidget(self.national_id, 3, 2, 1, 2)
        self.phone = QtWidgets.QLineEdit(self.EmployeeFrame)
        self.phone.setObjectName("phone")
        self.gridLayout_2.addWidget(self.phone, 9, 0, 1, 2)
        self.label_general_number = QtWidgets.QLabel(self.EmployeeFrame)
        self.label_general_number.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_general_number.setObjectName("label_general_number")
        self.gridLayout_2.addWidget(self.label_general_number, 0, 0, 1, 1)
        self.general_number = QtWidgets.QLineEdit(self.EmployeeFrame)
        self.general_number.setObjectName("general_number")
        self.gridLayout_2.addWidget(self.general_number, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.EmployeeFrame, 0, 0, 2, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_photo = QtWidgets.QLabel(self.tab)
        self.label_photo.setMinimumSize(QtCore.QSize(250, 200))
        self.label_photo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_photo.setObjectName("label_photo")
        self.verticalLayout.addWidget(self.label_photo)
        self.btn_upload_photo = QtWidgets.QPushButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icon-edit-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_upload_photo.setIcon(icon1)
        self.btn_upload_photo.setIconSize(QtCore.QSize(32, 32))
        self.btn_upload_photo.setObjectName("btn_upload_photo")
        self.verticalLayout.addWidget(self.btn_upload_photo)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setSpacing(8)
        self.buttons_layout.setObjectName("buttons_layout")
        self.saveBtn = QtWidgets.QPushButton(self.tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icon-ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon2)
        self.saveBtn.setIconSize(QtCore.QSize(32, 32))
        self.saveBtn.setObjectName("saveBtn")
        self.buttons_layout.addWidget(self.saveBtn)
        self.cancelBtn = QtWidgets.QPushButton(self.tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icon-undelete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelBtn.setIcon(icon3)
        self.cancelBtn.setIconSize(QtCore.QSize(32, 32))
        self.cancelBtn.setObjectName("cancelBtn")
        self.buttons_layout.addWidget(self.cancelBtn)
        self.gridLayout_4.addLayout(self.buttons_layout, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_visa = QtWidgets.QLabel(self.tab_2)
        self.label_visa.setStyleSheet("background-color: #f2f2f2;\n"
"border: 1px solid #d1d8e0;\n"
"border-radius: 4px;\n"
"font: 75 16pt \"Dubai\";\n"
"")
        self.label_visa.setAlignment(QtCore.Qt.AlignCenter)
        self.label_visa.setObjectName("label_visa")
        self.gridLayout_3.addWidget(self.label_visa, 3, 0, 1, 1)
        self.label_passport = QtWidgets.QLabel(self.tab_2)
        self.label_passport.setStyleSheet("background-color: #f2f2f2;\n"
"border: 1px solid #d1d8e0;\n"
"border-radius: 4px;\n"
"font: 75 16pt \"Dubai\";\n"
"")
        self.label_passport.setAlignment(QtCore.Qt.AlignCenter)
        self.label_passport.setObjectName("label_passport")
        self.gridLayout_3.addWidget(self.label_passport, 0, 0, 1, 1)
        self.visa_buttons = QtWidgets.QHBoxLayout()
        self.visa_buttons.setSpacing(12)
        self.visa_buttons.setObjectName("visa_buttons")
        self.btn_add_visa = QtWidgets.QPushButton(self.tab_2)
        self.btn_add_visa.setIcon(icon)
        self.btn_add_visa.setIconSize(QtCore.QSize(32, 32))
        self.btn_add_visa.setObjectName("btn_add_visa")
        self.visa_buttons.addWidget(self.btn_add_visa)
        self.btn_edit_visa = QtWidgets.QPushButton(self.tab_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/icon-compose.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit_visa.setIcon(icon4)
        self.btn_edit_visa.setIconSize(QtCore.QSize(32, 32))
        self.btn_edit_visa.setObjectName("btn_edit_visa")
        self.visa_buttons.addWidget(self.btn_edit_visa)
        self.btn_delete_visa = QtWidgets.QPushButton(self.tab_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/icon-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete_visa.setIcon(icon5)
        self.btn_delete_visa.setIconSize(QtCore.QSize(32, 32))
        self.btn_delete_visa.setObjectName("btn_delete_visa")
        self.visa_buttons.addWidget(self.btn_delete_visa)
        self.gridLayout_3.addLayout(self.visa_buttons, 5, 0, 1, 1)
        self.passport_buttons = QtWidgets.QHBoxLayout()
        self.passport_buttons.setSpacing(12)
        self.passport_buttons.setObjectName("passport_buttons")
        self.btn_add_passport = QtWidgets.QPushButton(self.tab_2)
        self.btn_add_passport.setIcon(icon)
        self.btn_add_passport.setIconSize(QtCore.QSize(32, 32))
        self.btn_add_passport.setObjectName("btn_add_passport")
        self.passport_buttons.addWidget(self.btn_add_passport)
        self.btn_edit_passport = QtWidgets.QPushButton(self.tab_2)
        self.btn_edit_passport.setIcon(icon4)
        self.btn_edit_passport.setIconSize(QtCore.QSize(32, 32))
        self.btn_edit_passport.setObjectName("btn_edit_passport")
        self.passport_buttons.addWidget(self.btn_edit_passport)
        self.btn_delete_passport = QtWidgets.QPushButton(self.tab_2)
        self.btn_delete_passport.setIcon(icon5)
        self.btn_delete_passport.setIconSize(QtCore.QSize(32, 32))
        self.btn_delete_passport.setObjectName("btn_delete_passport")
        self.passport_buttons.addWidget(self.btn_delete_passport)
        self.gridLayout_3.addLayout(self.passport_buttons, 2, 0, 1, 1)
        self.table_passport = QtWidgets.QTableWidget(self.tab_2)
        self.table_passport.setObjectName("table_passport")
        self.table_passport.setColumnCount(0)
        self.table_passport.setRowCount(0)
        self.gridLayout_3.addWidget(self.table_passport, 1, 0, 1, 1)
        self.table_visa = QtWidgets.QTableWidget(self.tab_2)
        self.table_visa.setObjectName("table_visa")
        self.table_visa.setColumnCount(0)
        self.table_visa.setRowCount(0)
        self.gridLayout_3.addWidget(self.table_visa, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnRefresh = QtWidgets.QPushButton(self.tab_3)
        self.btnRefresh.setMaximumSize(QtCore.QSize(180, 16777215))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/icon-refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRefresh.setIcon(icon6)
        self.btnRefresh.setIconSize(QtCore.QSize(32, 32))
        self.btnRefresh.setObjectName("btnRefresh")
        self.gridLayout_5.addWidget(self.btnRefresh, 0, 2, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.tab_3)
        self.titleLabel.setStyleSheet("background-color: #f2f2f2;\n"
"border: 1px solid #d1d8e0;\n"
"border-radius: 4px;\n"
"font: 75 16pt \"Dubai\";\n"
"")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_5.addWidget(self.titleLabel, 0, 0, 1, 2)
        self.documentsTree = QtWidgets.QListWidget(self.tab_3)
        self.documentsTree.setStyleSheet("border: 1px solid #d1d8e0;\n"
"border-radius: 10px;\n"
"font-size: 20px;\n"
"font-weight: bold; \n"
"padding: 10px;")
        self.documentsTree.setObjectName("documentsTree")
        self.gridLayout_5.addWidget(self.documentsTree, 1, 0, 4, 2)
        self.btnAddFile = QtWidgets.QPushButton(self.tab_3)
        self.btnAddFile.setMaximumSize(QtCore.QSize(180, 16777215))
        self.btnAddFile.setIcon(icon)
        self.btnAddFile.setIconSize(QtCore.QSize(32, 32))
        self.btnAddFile.setObjectName("btnAddFile")
        self.gridLayout_5.addWidget(self.btnAddFile, 1, 2, 1, 1)
        self.btnOpen = QtWidgets.QPushButton(self.tab_3)
        self.btnOpen.setMaximumSize(QtCore.QSize(180, 16777215))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/icon-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpen.setIcon(icon7)
        self.btnOpen.setIconSize(QtCore.QSize(32, 32))
        self.btnOpen.setObjectName("btnOpen")
        self.gridLayout_5.addWidget(self.btnOpen, 2, 2, 1, 1)
        self.btnDeleteFile = QtWidgets.QPushButton(self.tab_3)
        self.btnDeleteFile.setMaximumSize(QtCore.QSize(180, 16777215))
        self.btnDeleteFile.setIcon(icon5)
        self.btnDeleteFile.setIconSize(QtCore.QSize(32, 32))
        self.btnDeleteFile.setObjectName("btnDeleteFile")
        self.gridLayout_5.addWidget(self.btnDeleteFile, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(EditEmployeeDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EditEmployeeDialog)

    def retranslateUi(self, EditEmployeeDialog):
        _translate = QtCore.QCoreApplication.translate
        EditEmployeeDialog.setWindowTitle(_translate("EditEmployeeDialog", "تعديل بيانات الموظف"))
        self.label_name_ar.setText(_translate("EditEmployeeDialog", "الاسم بالعربية:"))
        self.label_birth_date.setText(_translate("EditEmployeeDialog", "تاريخ الميلاد:"))
        self.label_job_title.setText(_translate("EditEmployeeDialog", "المسمى الوظيفي:"))
        self.label_name_en.setText(_translate("EditEmployeeDialog", "الاسم بالإنجليزية:"))
        self.label_department.setText(_translate("EditEmployeeDialog", "القسم:"))
        self.label_role.setText(_translate("EditEmployeeDialog", "الدور:"))
        self.role_user.setText(_translate("EditEmployeeDialog", "فرد"))
        self.role_admin.setText(_translate("EditEmployeeDialog", "مسؤول"))
        self.birth_date.setDisplayFormat(_translate("EditEmployeeDialog", "dd/MM/yyyy"))
        self.label_phone.setText(_translate("EditEmployeeDialog", "رقم الهاتف:"))
        self.label_iban.setText(_translate("EditEmployeeDialog", "رقم الايبان:"))
        self.label_id_expiry.setText(_translate("EditEmployeeDialog", "تاريخ انتهاء الهوية:"))
        self.label_id_issue.setText(_translate("EditEmployeeDialog", "تاريخ إصدار الهوية:"))
        self.label_national_id.setText(_translate("EditEmployeeDialog", "رقم الهوية:"))
        self.id_expiry_date.setDisplayFormat(_translate("EditEmployeeDialog", "dd/MM/yyyy"))
        self.id_issue_date.setDisplayFormat(_translate("EditEmployeeDialog", "dd/MM/yyyy"))
        self.label_general_number.setText(_translate("EditEmployeeDialog", "الرقم العام:"))
        self.label_photo.setText(_translate("EditEmployeeDialog", "صورة الموظف"))
        self.btn_upload_photo.setText(_translate("EditEmployeeDialog", "رفع صورة"))
        self.saveBtn.setText(_translate("EditEmployeeDialog", "حفظ"))
        self.cancelBtn.setText(_translate("EditEmployeeDialog", "إلغاء"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("EditEmployeeDialog", "بيانات الموظف الأساسية"))
        self.label_visa.setText(_translate("EditEmployeeDialog", "بيانات التأشيرات"))
        self.label_passport.setText(_translate("EditEmployeeDialog", "بيانات جوازات السفر"))
        self.btn_add_visa.setText(_translate("EditEmployeeDialog", "إضافة تأشيرة"))
        self.btn_edit_visa.setText(_translate("EditEmployeeDialog", "تعديل تأشيرة"))
        self.btn_delete_visa.setText(_translate("EditEmployeeDialog", "حذف تأشيرة"))
        self.btn_add_passport.setText(_translate("EditEmployeeDialog", "إضافة جواز"))
        self.btn_edit_passport.setText(_translate("EditEmployeeDialog", "تعديل جواز"))
        self.btn_delete_passport.setText(_translate("EditEmployeeDialog", "حذف جواز"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("EditEmployeeDialog", "جوازات السفر والتأشيرات"))
        self.btnRefresh.setText(_translate("EditEmployeeDialog", "       تحديث  "))
        self.titleLabel.setText(_translate("EditEmployeeDialog", "📂   إدارة الملفات والمجلدات"))
        self.btnAddFile.setText(_translate("EditEmployeeDialog", "   إضافة ملف"))
        self.btnOpen.setText(_translate("EditEmployeeDialog", "   فتح الملف"))
        self.btnDeleteFile.setText(_translate("EditEmployeeDialog", "حذف الملف"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("EditEmployeeDialog", "وثائق الموظف"))
import img_rc
